apiVersion: v1
kind: Service
metadata:
  name: azure-monitoring-app-service
  labels:
    app: azure-monitoring-app
spec:
  type: NodePort
  selector:
    app: azure-monitoring-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30050
